version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: dockerized_rails
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - dockerized-rails-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - dockerized-rails-redis:/var/lib/redis/data

  dockerized_rails:
    build:
      context: .
    volumes:
      - ./dockerized_rails:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - dockerized_rails
    ports:
      - '8020:8020'

volumes:
  dockerized-rails-postgres:
  dockerized-rails-redis: